version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "customer-feedback"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fpwx9dxo239n"
s3_prefix = "customer-feedback"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
